import Link from 'next/link';
import {notFound} from 'next/navigation';
import {pages} from '../../lib/pages.mjs';
import {siteUrl,contactEmail,dateLabel} from '../../lib/content.mjs';
export function generateStaticParams(){return Object.keys(pages).map(page=>({page}));}
export async function generateMetadata({params}){const {page}=await params;const p=pages[page];return p?{title:p.title,description:p.intro,alternates:{canonical:'/'+page},openGraph:{title:p.title,description:p.intro,url:siteUrl+'/'+page,type:'website',locale:'hi_IN',siteName:'बात बाकी',images:[{url:'/images/baatbaaki-social.png',width:1200,height:630,alt:'BaatBaaki.com'}]}}:{};}
export default async function InfoPage({params}){
 const {page}=await params;const p=pages[page];if(!p)notFound();
 const schema={'@context':'https://schema.org','@type':page==='about'?'AboutPage':page==='contact'?'ContactPage':'WebPage','@id':siteUrl+'/'+page+'#page',url:siteUrl+'/'+page,name:p.title,description:p.intro,inLanguage:'hi-IN',dateModified:p.updatedAt,isPartOf:{'@type':'WebSite',name:'बात बाकी',url:siteUrl},breadcrumb:{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'होम',item:siteUrl+'/'},{'@type':'ListItem',position:2,name:p.title,item:siteUrl+'/'+page}]}};
 return <main id="main" className="wrap inner-page"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,'\\u003c')}}/><div className="breadcrumbs"><Link href="/">होम</Link><span>/</span>{p.title}</div><article className="info-page"><div className="page-heading"><span className="eyebrow">बात बाकी</span><h1>{p.title}<span className="red-period">.</span></h1><p>{p.intro}</p><p className="updated">अपडेट: <time dateTime={p.updatedAt}>{dateLabel(p.updatedAt)}</time></p></div>{page==='contact'&&<a className="button" href={'mailto:'+contactEmail}>{contactEmail}</a>}{p.sections.map(([title,text])=><section key={title}><h2>{title}</h2><p>{text}</p></section>)}<nav aria-label="संबंधित जानकारी"><h2>और जानकारी</h2>{['about','contact','editorial-policy','corrections','privacy','terms','disclaimer','advertising-policy'].filter(slug=>slug!==page).map(slug=><p key={slug}><Link href={'/'+slug}>{pages[slug].title}</Link></p>)}</nav></article></main>
}
