import fs from 'node:fs';
import path from 'node:path';
export const categories = [{"slug": "india", "name": "देश-दुनिया", "seoTitle": "देश-दुनिया की खबरें और सरकारी योजनाओं की जानकारी", "description": "भारत और दुनिया की बड़ी खबरें, नरेंद्र मोदी की सार्वजनिक भूमिका, सरकारी योजनाएं और जरूरी घोषणाएं। स्रोतों के साथ समझें कि नए बदलाव आपके लिए क्या मायने रखते हैं।", "intro": "सरकारी घोषणा पढ़ते समय पात्रता, लागू होने की तारीख और आधिकारिक आवेदन प्रक्रिया अलग-अलग जांचें। यहां योजनाओं की शर्तों, जरूरी दस्तावेज और वैश्विक घटनाओं का सरल संदर्भ मिलता है।"}, {"slug": "education", "name": "शिक्षा और नौकरी", "seoTitle": "शिक्षा और नौकरी: NEET, प्रवेश और परीक्षा की जानकारी", "description": "NEET की तैयारी, काउंसलिंग, कॉलेज प्रवेश और छात्रवृत्ति की हिंदी जानकारी। आवेदन की तारीख, पात्रता और आधिकारिक सूचना तक पहुंचने के तरीके समझें।", "intro": "तैयारी कर रहे हैं तो पहले सिलेबस और रिविजन की गाइड पढ़ें। परीक्षा के बाद काउंसलिंग और सीट के नियम देखें। प्रवेश या छात्रवृत्ति के लिए संबंधित संस्था की नई सूचना से अंतिम तारीख मिलाएं।"}, {"slug": "auto", "name": "ऑटो", "seoTitle": "कार, बाइक और EV: कीमत, बुकिंग और खरीदारी गाइड", "description": "कार, बाइक और इलेक्ट्रिक वाहनों की खबरें, कीमत, वेरिएंट, बुकिंग और सब्सिडी की जानकारी। वाहन खरीदने से पहले खर्च और उपलब्धता का फर्क समझें।", "intro": "एक्स-शोरूम कीमत में बीमा और रजिस्ट्रेशन शामिल नहीं होते। यहां वेरिएंट चुनने, बुकिंग की शर्तें समझने और EV योजना की पात्रता जांचने के लिए प्रकाशित गाइड मिलेंगी।"}, {"slug": "cricket", "name": "क्रिकेट", "seoTitle": "क्रिकेट की खबरें, खिलाड़ियों के रिकॉर्ड और यादगार पारियां", "description": "भारतीय क्रिकेट, विराट कोहली, रोहित शर्मा, धोनी और अन्य खिलाड़ियों के रिकॉर्ड की हिंदी जानकारी। मैच की तारीख, आंकड़े और उपलब्धियों का संदर्भ समझें।", "intro": "टेस्ट, वनडे और T20 के आंकड़े अलग होते हैं। किसी रिकॉर्ड की तुलना करते समय फॉर्मेट, विरोधी टीम और तारीख देखें। यहां ऐतिहासिक पारियों और बड़ी उपलब्धियों की स्रोत आधारित जानकारी पढ़ें।"}, {"slug": "entertainment", "name": "मनोरंजन", "seoTitle": "बॉलीवुड, फिल्में और OTT: कलाकारों की खबरें और गाइड", "description": "बॉलीवुड और भारतीय फिल्मों की खबरें, कलाकारों के परिचय, यादगार किरदार और OTT गाइड। रिलीज की पुष्ट जानकारी और चर्चाओं का फर्क आसान हिंदी में समझें।", "intro": "नई फिल्म की रिलीज और OTT उपलब्धता के लिए निर्माता या स्ट्रीमिंग मंच की सूचना देखें। पुराने किरदारों की गाइड में कहानी का संदर्भ मिलता है; किसी चर्चा को पुष्ट घोषणा मानने से पहले स्रोत जांचें।"}, {"slug": "business", "name": "पैसा और कारोबार", "seoTitle": "पैसा और कारोबार: कमाई, लोन और बिजनेस गाइड", "description": "कारोबार की खबरें, ऑनलाइन काम, छोटे व्यवसाय, लोन और लाभांश की हिंदी जानकारी। पात्रता, खर्च, भुगतान और जोखिम समझकर अपने अगले कदम तय करें।", "intro": "काम से कमाई शुरू करने में कौशल, ग्राहक और खर्च की भूमिका होती है। गाइड में शुरुआती कदम और भुगतान की सावधानियां पढ़ें। लोन या निवेश से जुड़ी शर्तें संबंधित संस्था के पास दोबारा जांचें।"}];
export function getArticles(){return fs.readdirSync(path.join(process.cwd(),'content/articles')).filter(f=>f.endsWith('.json')).map(f=>JSON.parse(fs.readFileSync(path.join(process.cwd(),'content/articles',f),'utf8'))).filter(a=>a.status==='published').sort((a,b)=>b.publishedAt.localeCompare(a.publishedAt));}
export function getArticle(slug){return getArticles().find(a=>a.slug===slug);}
export const siteUrl=(process.env.SITE_URL||'https://baatbaaki.com').replace(/\/$/,'');
export const indexable=process.env.SITE_INDEXABLE!=='false';
export function dateLabel(date){return new Intl.DateTimeFormat('hi-IN',{day:'numeric',month:'long',year:'numeric',timeZone:'Asia/Kolkata'}).format(new Date(date));}
export function readTime(article){return Math.max(2,Math.ceil(article.body.split(/\s+/).length/180));}
export function categoryName(slug){return categories.find(c=>c.slug===slug)?.name||'खबर';}

export const contactEmail=process.env.CONTACT_EMAIL?.trim()||'info@baatbaaki.com';

export function dateTimeLabel(date){return new Intl.DateTimeFormat('hi-IN',{day:'numeric',month:'long',year:'numeric',hour:'2-digit',minute:'2-digit',timeZone:'Asia/Kolkata'}).format(new Date(date))+' IST';}
